### ISSUE TITLE
FilWip not building on 64 bit

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/FilWip#15]
After uncommenting !x86_64 in FilWip recipe:

waiting for build package filwip-1.0.0-7 to be activated
Building ...
make: Entering directory '/sources/FilWip-e5e8bc31c3f356b603041be8883ce5c7df46ce97/Source'
g++ -c BubbleHelp/BubbleHelper.cpp -iquote./  -iquote./  -iquoteBubbleHelp/  -iquoteobjects.x86_64-cc5-release/   -O3    -o "objects.x86_64-cc5-release/BubbleHelper.o"
g++ -c EraserLooper.cpp -iquote./  -iquote./  -iquoteBubbleHelp/  -iquoteobjects.x86_64-cc5-release/   -O3    -o "objects.x86_64-cc5-release/EraserLooper.o"
g++ -c FilWip.cpp -iquote./  -iquote./  -iquoteBubbleHelp/  -iquoteobjects.x86_64-cc5-release/   -O3    -o "objects.x86_64-cc5-release/FilWip.o"
g++ -c FileLooper.cpp -iquote./  -iquote./  -iquoteBubbleHelp/  -iquoteobjects.x86_64-cc5-release/   -O3    -o "objects.x86_64-cc5-release/FileLooper.o"
BubbleHelp/BubbleHelper.cpp: In constructor 'BubbleHelper::BubbleHelper()':
BubbleHelp/BubbleHelper.cpp:53:30: error: cannot convert 'long int*' to 'int32* {aka int*}' for argument '1' to 'int32 atomic_add(int32*, int32)'
  if (atomic_add (&runcount, 1) == 0)
                              ^
BubbleHelp/BubbleHelper.cpp:56:81: error: invalid conversion from 'long int (*)(void*)' to 'thread_func {aka int (*)(void*)}' [-fpermissive]
   helperthread = spawn_thread (_helper, "Bubble_Helper", B_NORMAL_PRIORITY, this);
                                                                                 ^
In file included from /boot/system/develop/headers/os/interface/InterfaceDefs.h:10:0,
                 from /boot/system/develop/headers/os/app/Application.h:10,
                 from BubbleHelp/BubbleHelper.cpp:25:
/boot/system/develop/headers/os/kernel/OS.h:331:18: note:   initializing argument 1 of 'thread_id spawn_thread(thread_func, const char*, int32, void*)'
 extern thread_id spawn_thread(thread_func, const char *name, int32 priority,
                  ^
BubbleHelp/BubbleHelper.cpp: In destructor 'virtual BubbleHelper::~BubbleHelper()':
BubbleHelp/BubbleHelper.cpp:107:27: error: cannot convert 'long int*' to 'int32* {aka int*}' for argument '1' to 'int32 atomic_add(int32*, int32)'
  atomic_add (&runcount, -1);
                           ^
BubbleHelp/BubbleHelper.cpp: In member function 'void BubbleHelper::Helper()':
BubbleHelp/BubbleHelper.cpp:213:41: error: no matching function for call to 'BTextView::GetMouse(BPoint*, ulong*)'
     textview->GetMouse (&where, &buttons);
                                         ^
In file included from /boot/system/develop/headers/os/interface/Window.h:11:0,
                 from BubbleHelp/BubbleHelper.cpp:26:
/boot/system/develop/headers/os/interface/View.h:187:12: note: candidate: void BView::GetMouse(BPoint*, uint32*, bool)
    void    GetMouse(BPoint* location, uint32* buttons,
            ^
/boot/system/develop/headers/os/interface/View.h:187:12: note:   no known conversion for argument 2 from 'ulong* {aka long unsigned int*}' to 'uint32* {aka unsigned int*}'
BubbleHelp/BubbleHelper.cpp:250:46: error: no matching function for call to 'BTextView::GetMouse(BPoint*, ulong*)'
         textview->GetMouse (&where2, &buttons);
                                              ^
In file included from /boot/system/develop/headers/os/interface/Window.h:11:0,
                 from BubbleHelp/BubbleHelper.cpp:26:
/boot/system/develop/headers/os/interface/View.h:187:12: note: candidate: void BView::GetMouse(BPoint*, uint32*, bool)
    void    GetMouse(BPoint* location, uint32* buttons,
            ^
/boot/system/develop/headers/os/interface/View.h:187:12: note:   no known conversion for argument 2 from 'ulong* {aka long unsigned int*}' to 'uint32* {aka unsigned int*}'
BubbleHelp/BubbleHelper.cpp:265:45: error: no matching function for call to 'BTextView::GetMouse(BPoint*, ulong*)'
         textview->GetMouse (&where2,&buttons);
                                             ^
In file included from /boot/system/develop/headers/os/interface/Window.h:11:0,
                 from BubbleHelp/BubbleHelper.cpp:26:
/boot/system/develop/headers/os/interface/View.h:187:12: note: candidate: void BView::GetMouse(BPoint*, uint32*, bool)
    void    GetMouse(BPoint* location, uint32* buttons,
            ^
/boot/system/develop/headers/os/interface/View.h:187:12: note:   no known conversion for argument 2 from 'ulong* {aka long unsigned int*}' to 'uint32* {aka unsigned int*}'
/boot/system/develop/etc/makefile-engine:291: recipe for target 'objects.x86_64-cc5-release/BubbleHelper.o' failed
make: *** [objects.x86_64-cc5-release/BubbleHelper.o] Error 1
make: *** Waiting for unfinished jobs....
EraserLooper.cpp: In member function 'void EraserLooper::EraseList(bool)':
EraserLooper.cpp:102:59: error: call of overloaded 'RemoveItem(long int)' is ambiguous
   const char *path = (const char*)entryList.RemoveItem (0L);
                                                           ^
In file included from /boot/system/develop/headers/os/interface/Gradient.h:11:0,
                 from /boot/system/develop/headers/os/interface/View.h:15,
                 from /boot/system/develop/headers/os/interface/StatusBar.h:10,
                 from EraserLooper.cpp:32:
/boot/system/develop/headers/os/support/List.h:28:12: note: candidate: bool BList::RemoveItem(void*)
    bool    RemoveItem(void* item);
            ^
/boot/system/develop/headers/os/support/List.h:29:13: note: candidate: void* BList::RemoveItem(int32)
    void*    RemoveItem(int32 index);
             ^
/boot/system/develop/etc/makefile-engine:291: recipe for target 'objects.x86_64-cc5-release/EraserLooper.o' failed
make: *** [objects.x86_64-cc5-release/EraserLooper.o] Error 1
make: Leaving directory '/sources/FilWip-e5e8bc31c3f356b603041be8883ce5c7df46ce97/Source'
[Errno -2147459069] No such file or directory: '/boot/home/haikuports/haiku-apps/filwip/work-1.0.0'
Error: Build has failed - stopping.

**Comment by korli** [comment]
@Vidrep 
RemoveItem (0L)   =>  RemoveItem ((int32)0)

**Comment by Vidrep** [comment]
Tested as building and working on Haiku x86_64.

**Comment by korli** [comment]
The Haikuports patch set needs upstreaming :)

**Comment by Vidrep** [comment]
I know this is probably not the place to thank devs, but I'll do it anyway. Thanks!
I'd also like to mention that this commit appears not to have been added:
commit 046b5f6df9e2566031cd48fc802ded760bb48696

**Comment by Vidrep** [comment]
Tested filwip-1.0.0-8-x86_64.hpkg as working OK.
Can this package be added to HaikuDepot, please?

**Comment by Vidrep** [comment]
Humdinger added 64 bit package to HaikuDepot. 
x86_gcc2 package needs to be updated and added as well.
