### ISSUE TITLE
Add option to delete last Webpositive session

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/FilWip#16]
Add option to delete last Webpositive session

/boot/home/config/settings/WebPositive/Session

**Comment by Vidrep** [comment]
After reading the documentation, I found the solution was simple - add this to the Webpositive plugin:

[Session]
FILE=/boot/home/config/settings/WebPositive/Session
EXCLUDE FILE=
RECURSE=

**Comment by diversys** [comment]
Please create a PR for that.

**Comment by Vidrep** [comment]
I'm on IRC now. I'll need guidance

**Comment by Vidrep** [comment]
Got it figured out. PR created
