### ISSUE TITLE
Cannot set up FilWip to delete MediaPlayer Current Playlist

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/FilWip#19]
;; MediaPlayer plugin

[MediaPlayer]
TYPE=heirarchical
CHECK INSTALL OF=

[MediaPlayer Playlist]
FOLDER=/boot/home/config/settings/MediaPlayer Current Playlist
EXCLUDE FILE=
RECURSE=

**Comment by pulkomandy** [comment]
You have a typo:

    TYPE=heirarchical

instead of :

    TYPE=hierarchical

**Comment by Vidrep** [comment]
Typo fixed. Below is screenshot of where I'm at with it:

![mediaplayer](https://user-images.githubusercontent.com/13264393/28492689-f5023a84-6ec4-11e7-9ca6-0efa076d196c.png)

**Comment by humdingerb** [comment]
Maybe you have to escape the blanks in the path. Have you tried:
`FOLDER=/boot/home/config/settings/MediaPlayer\ Current\ Playlist`
Just a guess, haven't looked into it at all.

**Comment by Vidrep** [comment]
Attached is the MediaPlayer plugin that achieves the result I was looking for.
[10_media player.txt](https://github.com/HaikuArchives/FilWip/files/1271744/10_media.player.txt)

**Comment by Vidrep** [comment]
Enhancement added with this commit:
https://github.com/HaikuArchives/FilWip/commit/1ba40e0ff378c29c8c0f4836c49fe58bd343c3be
