### ISSUE TITLE
Use layout and modernize the interface [RFC]

### ISSUE THREAD

**Issue by janus2** [HaikuArchives/FilWip#27]
![prototype](https://user-images.githubusercontent.com/10423645/42421041-2ba8bd00-82cf-11e8-8985-a62a5f26aacc.png)

**Comment by janus2** [comment]
![with or without](https://user-images.githubusercontent.com/10423645/42422566-d832f41e-82e8-11e8-864e-c04ebe06fc55.png)

**Comment by humdingerb** [comment]
I think the intro text wouldn't hurt...
And maybe the BBox wasn't bad after all... maybe just without the "Remove" label?

**Comment by janus2** [comment]
![without remove](https://user-images.githubusercontent.com/10423645/42422861-ffa1cf2e-82ee-11e8-9f07-49469034ca84.png)

**Comment by janus2** [comment]
## WIP Some new icons
![wip new icons](https://user-images.githubusercontent.com/10423645/42424012-64b26d28-8304-11e8-9081-f05315c3808d.png)

**Comment by KevinAdams05** [comment]
This looks nice. What about using a normal toolbar for the icons, instead of having them aligned on the right?

**Comment by janus2** [comment]
I thought about that, but without a menu it look awful.

![horizontal](https://user-images.githubusercontent.com/10423645/42494768-7f08046c-8421-11e8-81fa-7b19e9634239.png)

**Comment by janus2** [comment]
### New presets icon

![old vs new presets icons](https://user-images.githubusercontent.com/10423645/42496967-f998d94e-8427-11e8-981a-da5ce0146de5.png)

**Comment by KevinAdams05** [comment]
You're the right, the horizontal toolbar doesn't look very good. 

The new icon is nice!

**Comment by janus2** [comment]
Fixed in #28
