### ISSUE TITLE
Remove unneeded preferences

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/FilWip#29]
I'm not really a user of FilWip, but are all those preferences really needed?

- "Report": does it have to be that fine grained? Maybe having a report with all that info, yes/no, would suffice.
- "Loopers": strikes me as extremely technical, and way beyond anything a regular FilWip user can grasp.
- "Remember": would it hurt to have all these options activated and do away with the preference?
- "Plugins": the first three don't seem to be essential for the end user.

Maybe some of the advanced options could be command line options for debugging purposes.
Maybe the few remaining options could even be in just a simple window with checkboxes and possibly BBoxes.

**Comment by janus2** [comment]
![mockup](https://user-images.githubusercontent.com/10423645/42694344-64a83ae0-86b2-11e8-9358-20329976c200.png)

**Comment by janus2** [comment]
I'll keep the older Preferences Window as an easter egg ;-)

**Comment by humdingerb** [comment]
Cool. Never know if one of those more obscure options come in handy one day. :)

**Comment by Vidrep** [comment]
We could have a optional "advanced" view setting

**Comment by janus2** [comment]
There is already, please don't use that!
