### ISSUE TITLE
Size of "previous system state" intermittently "0" until selected

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/FilWip#35]
Upon opening FilWip, the size of the previous system state intermittently remains at 0 bytes, until the item is selected, then it is calculated. The other items seem not to be affected.

**Comment by janus2** [comment]
If you had the old version please delete the config file in ~/config/settings/FilWip/FilWip_settings and retry. This should fix the problem.

This problem is present in the old version too, but there are so many redraw glitches that goes unnoticed.

**Comment by Vidrep** [comment]
I deleted all traces of my previous installation. That appears to have fixed the issue, as well as one I was seeing with zoom.
